replicaCount: 1

image:
  repository: provisioning
  tag: "1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

route:
  enabled: true
  host: ""
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

config:
  pythonPath: /app/src
  git:
    namespaceRepo: ""
    monitoringRepo: ""
    argocdRepo: ""
  gitActions:
    basePath: /tmp/git-repos
  provisioning:
    logLevel: INFO

# Keep false in Git. Create the Git Secret separately with oc.
secret:
  create: false
  existingSecret: provisioning-git

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  enabled: true
  path: /docs
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /docs
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}
